language: cpp
os: linux

addons:
  apt:
    packages:
    - gfortran

before_install:
    - git clone https://gist.github.com/tkralphs/13d4529b4d4e8889f3a6 scripts
    - bash scripts/get.dependencies.sh fetch

install: bash scripts/get.dependencies.sh build

script: make test
